### ISSUE TITLE
Does this actually support IE7?

### ISSUE THREAD

**Issue by danielcrisp** [cvn/angular-shims-placeholder#22]
You state this in the readme:

> such as IE9, IE8, and below

But it seems it doesn't actually work in IE7. Can you confirm?

I also tried the demo page but it errors because it uses `console` so I can't tell if it should be working

**Comment by jrief** [comment]
It uses only AngularJS function, so if AngularJS works for IE7, it should work. Well unless console.log....

I don't have any IE7 around, so I can't test this right now.

**Comment by danielcrisp** [comment]
Ok thanks, maybe I've got a problem elsewhere.. I'll have a look and let you know

**Comment by cvn** [comment]
The `console.log` on the demo page is inside an `if (console) { }` conditional, so that's not the problem there. The demo page loads Angular 1.2.28 for IE8 and below, and Angular dropped support for IE7 in 1.2, I think that's why.

I've never tested angular-shims-placeholder with Angular 1.1.x or IE7, so I have no idea if it will work. If you try this, let us know and I'll update the readme.

**Comment by danielcrisp** [comment]
You've got to use `if (window.console) { }` otherwise it still errors

Anyway I've forked it and got it working nicely in IE7 and v1.0.8, with only a few small changes. I'll do a PR for you to take a look

**Comment by danielcrisp** [comment]
Here you go #23, most of it is changes to them demo page rather than the directive itself.

Would be amazing (for me) if you could merge it as I have to support IE7 in a number of projects and I think you've done some great work here.

**Comment by cvn** [comment]
As of v0.4.2, the directive supports IE7 and Angular 1.0.8. Thanks for all the work, @danielcrisp!
